version: "3.9"

services:
  erebus:
    profiles:
      - "staging"
      - "production"
    image: "erebus:latest"
    container_name: "erebus"
    hostname: "erebus"
    restart: "unless-stopped"
    networks:
      - "erebus"
    expose:
      - "8080"
    command:
      - "erebus"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8080"
    environment:
      TZ: "${TZ}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_HOST: "${POSTGRES_HOST}"
      POSTGRES_PORT: "${POSTGRES_PORT}"
      POSTGRES_DB: "${POSTGRES_DB}"

  nginx:
    profiles:
      - "staging"
      - "production"
    image: "nginx:1.23.2-alpine"
    container_name: "nginx"
    hostname: "nginx"
    restart: "unless-stopped"
    depends_on:
      - "erebus"
    networks:
      - "erebus"
    ports:
      - "80:80"
    environment:
      TZ: "${TZ}"
      NGINX_SERVER_NAME: "${NGINX_SERVER_NAME}"
    volumes:
      - type: "bind"
        source: "./nginx"
        target: "/etc/nginx/templates"
        read_only: true
      - type: "volume"
        source: "nginx-log"
        target: "/var/log/nginx/${NGINX_SERVER_NAME}"
        read_only: false

  postgres:
    profiles:
      - "development"
      - "staging"
      - "production"
    image: "postgres:15.1-alpine3.16"
    container_name: "postgres"
    hostname: "postgres"
    restart: "unless-stopped"
    networks:
      - "erebus"
    ports:
      - "5432:5432"
    healthcheck:
      test: "pg_isready -U $POSTGRES_USER"
      interval: "5s"
      timeout: "60s"
      retries: 5
    environment:
      TZ: "${TZ}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - type: "volume"
        source: "postgres-data"
        target: "/var/lib/postgresql/data"
        read_only: false

networks:
  erebus:
    name: "erebus"
    driver: "bridge"
    driver_opts:
      com.docker.network.bridge.name: "br0"

volumes:
  postgres-data:
    name: "postgres-data"
    driver: "local"

  nginx-log:
    name: "nginx-log"
    driver: "local"
